### ISSUE TITLE
Error when removing element

### ISSUE THREAD

**Issue by carlosveny** [elbobo/aframe-multisrc-component#1]
Hello, I'm trying to remove an element from JavaScript that has the multisrc component attached but I get the following error: `Uncaught TypeError: this.el is undefined`. The component itself works well but I really need to delete those elements with the multisrc component attached. Any help?

**Comment by elbobo** [comment]
Hi, I'm sorry its been a long time since I created this (also been a while since I used a-frame). I'm not sure I understand what issue are you are having. 

Is it that you cannot remove the component?

Or you can't remove an element with the component attached?

If the former its definitely possible I didn't include the remove function. You could probably modify the code to include that quite easily.

If the latter that is very strange and I'd have to investigate.

Could you describe step by step what you are doing?

**Comment by carlosveny** [comment]
Hello and thanks for your response,
I've kinda "fixed" it. I don't like my solution but it works.
Basically to reproduce the error you have to:
1. Define a box in HTML and attach your "multisrc" component.
2. Assign, let's say, 2 different textures to any of the sides of the box. (The component works as intended).
3. Remove the element that has the "multisrc" component attached.
4. You will get the following error: `Uncaught TypeError: this.el is undefined` in line 386 of your JS code.

I've also tried to remove the component itself before removing the whole element but I still get that error. Checking your code I see that in lines 383-386 there is the following:
```
//removes all animation event listeners at once
var animationEventsArray = ['animationbegin', 'animationstart', 'animationcomplete', 'animationend']  
animationEventsArray.forEach(function(event) {  
        this.el.addEventListener(event, this.materialChangedByAnimation)  
});
```
That's the part of your code that throws the error. So basically I've commented those lines and it works. I don't know if there will be problems with the animation but I'm not using any animation so I think I'm good to go.
